import React from 'react';
import { MapPin, Calendar, Tag, Sparkles, ShieldCheck, MessageSquare, ArrowRight } from 'lucide-react';
import { BrowseItem } from '../../data/mockBrowseItems';

interface ItemOverviewProps {
  item: BrowseItem;
  onInitiateClaim: () => void;
}

export const ItemOverview: React.FC<ItemOverviewProps> = ({ item, onInitiateClaim }) => {
  const isLost = item.status === 'LOST';

  return (
    <div className="w-full space-y-6">
      
      {/* Category Tag & Title */}
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400">
          <Tag className="w-3.5 h-3.5 text-violet-400 shrink-0" />
          <span>{item.category}</span>
          {item.metadata.brand && (
            <>
              <span>•</span>
              <span className="text-slate-300">{item.metadata.brand}</span>
            </>
          )}
        </div>

        <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-white font-sans tracking-tight">
          {item.name}
        </h1>
      </div>

      {/* Location & Date Bar */}
      <div className="flex flex-wrap gap-4 text-xs font-semibold text-slate-300 border-y border-indigo-950/80 py-3.5">
        <div className="flex items-center gap-1.5">
          <MapPin className="w-4 h-4 text-violet-400 shrink-0" />
          <span>{item.location}</span>
        </div>
        <div className="flex items-center gap-1.5">
          <Calendar className="w-4 h-4 text-cyan-400 shrink-0" />
          <span>Reported on {item.date}</span>
        </div>
      </div>

      {/* Description */}
      <div className="space-y-1.5">
        <h3 className="text-xs font-extrabold uppercase tracking-widest text-slate-400">Description</h3>
        <p className="text-slate-300 text-sm md:text-base leading-relaxed">{item.description}</p>
      </div>

      {/* Match Confidence Explanation Box (If matchConfidence exists) */}
      {item.matchConfidence && (
        <div className="bg-[#0B0F1B]/95 border border-violet-500/40 rounded-2xl p-4 space-y-2 shadow-md">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-violet-300 font-extrabold text-xs tracking-wider uppercase">
              <Sparkles className="w-4 h-4 text-violet-400" />
              <span>Potential Match Identified</span>
            </div>
            <span className="text-sm font-black text-violet-400 bg-violet-950/60 px-2.5 py-0.5 rounded-lg border border-violet-500/40">
              {item.matchConfidence}% Match
            </span>
          </div>
          <p className="text-slate-400 text-xs leading-relaxed">
            This match is generated by location and attribute similarity. Matching signals highlight potential connections, but ownership must be verified before an item is transferred.
          </p>
        </div>
      )}

      {/* Action Buttons */}
      <div className="space-y-3 pt-2">
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={onInitiateClaim}
            className="flex-1 inline-flex items-center justify-center gap-2 py-3.5 px-6 rounded-xl bg-gradient-to-r from-violet-600 via-indigo-600 to-cyan-500 text-white font-bold text-sm hover:opacity-95 transition-all shadow-[0_0_25px_rgba(124,58,237,0.4)]"
          >
            <span>{isLost ? 'This is my item' : 'This might be mine'}</span>
            <ArrowRight className="w-4 h-4" />
          </button>

          <button
            onClick={() => alert('Contact inquiry sent to community moderation desk.')}
            className="inline-flex items-center justify-center gap-2 py-3.5 px-5 rounded-xl bg-[#0B0F1B] border border-indigo-900/60 text-slate-200 font-bold text-sm hover:text-white hover:border-violet-500/50 transition-all"
          >
            <MessageSquare className="w-4 h-4 text-cyan-400" />
            <span>Ask About Item</span>
          </button>
        </div>

        {/* Verification Trust Message */}
        <div className="flex items-center gap-2 text-xs text-slate-400 bg-[#080B14] p-3 rounded-xl border border-indigo-950/80">
          <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>Ownership verification is required before an item can be claimed and returned.</span>
        </div>
      </div>

    </div>
  );
};
